#page title
page_title                                : Flip Me iOS Game                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6499492638                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
  #playstore_link                            :                                           # Enter Google Play Store URL.
  #presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-logo-2.png             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Flip Me - Concentration Game                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A fun, simple, and engaging concentration game featuring delightful kids' drawings and adorable animations

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Steven Morin                              
your_link                                 : https://www.linkedin.com/in/steven-morin-fr
your_city                                 : France. © 2024 All Right Reserved.
email_address                             : mousquetaire.softwares@gmail.com
  #facebook_username                         :                                           
  #instagram_username                        : ebaehr
  #twitter_username                          : ebaehr
github_username                           : stvim
  #youtube_username                          :
  #mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Original
    description                           : Rediscover a classic game with a unique twist, featuring playful gestures and multiple ways to play
    fontawesome_icon_name                 : sync

  - title                                 : Progressive
    description                           : Offers numerous levels ranging from very easy to very hard
    fontawesome_icon_name                 : play-circle

  - title                                 : For everyone
    description                           : Suitable for young kids and adults alike, you can even play together!
    fontawesome_icon_name                 : link

  - title                                 : Engaging
    description                           : Unlock a plethora of mystery images and levels by playing more
    fontawesome_icon_name                 : adjust
  
  - title                                 : iPad or iPhone
    description                           : Designed for both iPad & iPhone, in portrait or landscape orientation
    fontawesome_icon_name                 : mobile
    
  - title                                 : Stimulate Your Brain
    description                           : Can you beat your previous best score?
    fontawesome_icon_name                 : star

#  - title                                 : Smart App Banner
#    description                           : Display a smart app banner on iOS devices.
#    fontawesome_icon_name                 : arrow-alt-circle-down
#
#  - title                                 : Social Links
#    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : magic
#
#  - title                                 : FontAwesome Support
#    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
#    fontawesome_icon_name                 : info-circle
#
#  - title                                 : # New Feature Title
#    description                           : # New Feature Description
#    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/background-banner.png                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
